-- Create database (run once if needed)
CREATE DATABASE IF NOT EXISTS okekirim CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE okekirim;

-- Drivers
CREATE TABLE IF NOT EXISTS drivers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(64) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,  
  address TEXT DEFAULT NULL,
  vehicle VARCHAR(128) DEFAULT NULL,
  vehicleType VARCHAR(64) DEFAULT NULL,
  vehicleYear VARCHAR(16) DEFAULT NULL,
  status VARCHAR(32) DEFAULT 'aktif',
  joinDate DATE DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Documents
CREATE TABLE IF NOT EXISTS documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vehicle VARCHAR(128) DEFAULT NULL,
  type VARCHAR(128) DEFAULT NULL,
  expiry DATE DEFAULT NULL,
  renewalCost INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Services
CREATE TABLE IF NOT EXISTS services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vehicle VARCHAR(128) DEFAULT NULL,
  driver VARCHAR(255) DEFAULT NULL,
  type VARCHAR(128) DEFAULT NULL,
  date DATE DEFAULT NULL,
  cost INT DEFAULT NULL,
  status VARCHAR(32) DEFAULT 'terjadwal',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Schedules (Tarikan + Hutang)
CREATE TABLE IF NOT EXISTS schedules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  driver VARCHAR(255) DEFAULT NULL,
  vehicle VARCHAR(128) DEFAULT NULL,
  date DATE DEFAULT NULL,
  origin VARCHAR(255) DEFAULT NULL,
  destination VARCHAR(255) DEFAULT NULL,
  rit VARCHAR(32) DEFAULT NULL,
  orderType VARCHAR(32) DEFAULT 'online',
  fare INT DEFAULT 0,
  status VARCHAR(32) DEFAULT 'nunggak',
  companyShare INT DEFAULT 0,
  paidCompanyAmount INT DEFAULT 0,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

